# Generated by Django 3.0.5 on 2020-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='college_url',
            field=models.URLField(blank=True, help_text='eg. Pastes Event URL If Want', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_poster_image',
            field=models.ImageField(default='defaults/defaults.png', help_text='Upload a 800 x 400 Image', upload_to='poster'),
        ),
    ]
